
INSERT INTO lab_p_pruebas VALUES (2, 4, '2498', 'antibiograma (disco)', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (3, 4, '8215', 'antibiograma', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (4, 5, '2499', 'antibiograma (mic) metodo manual', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (5, 6, '01', 'rastreo de anticuerpos irregulares', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (6, 6, '02', 'coombs indirecto', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (7, 7, '01', 'grupo  sanguineo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (8, 7, '02', 'factor rh', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (9, 7, '03', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (10, 7, '04', 'células cde', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (11, 8, '04', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (12, 8, '01', 'baciloscopia de esputo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (13, 8, '02', 'baciloscopia de jugo gastrico', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (14, 8, '03', 'baciloscopia de l.c.r', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (15, 8, '80481', 'baciloscopia 2', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (16, 8, 'IIO', 'calidad de la muestra', 1, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (17, 8, '6795', 'bacilo de hanse', 4, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (18, 8, '699', 'baciloscopia coloración acido alcohol-resistente (ziehl-neel', 4, '1', true);
INSERT INTO lab_p_pruebas VALUES (19, 8, '4144', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (20, 8, '80482', 'baciloscopia 3', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (21, 8, '8048', 'baciloscopia 1', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (22, 9, '5003', 'coloracion de gram', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (23, 9, '48', 'coloracion de gram', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (24, 9, '4144', 'observaciones', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (25, 9, '707', 'coloración gram y lectura para cualquier muestra', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (26, 9, '03', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (27, 9, '01', 'respuesta leucocitaria', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (28, 9, '02', 'gram', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (29, 10, '01', 'tinta china', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (30, 10, '02', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (31, 11, '90111', 'baciloscopia coloracion acido alcohol resistente', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (32, 11, '1', 'muestra 1', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (33, 11, '2', 'muestra 2', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (34, 11, '3', 'muestra 3', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (90, 25, '06', 'hematies', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (677, 122, '9999', 'talla', 4, 'cm', false);
INSERT INTO lab_p_pruebas VALUES (873, 145, '08', 'glucosa', 1, '', true);
INSERT INTO lab_p_pruebas VALUES (1155, 227, '01', 'positivo', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (1246, 252, '4144', 'observaciones', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (1632, 337, '2006', 'cilindros', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (35, 12, '01', 'coprocultivo:', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (36, 12, '02', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (37, 12, '8106', 'cultivo de materia fecal -coprocultivo- incluye identificac', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (38, 13, '01', 'cultivo de líquido cefalorraquideo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (39, 13, '02', 'observación:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (40, 14, '01', 'tipo de muestra', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (41, 14, '02', 'resultado', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (42, 14, '03', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (43, 14, '2531', 'cultivo especiales para otros microorganismos', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (44, 14, '45507', 'cultivo rectovaginal', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (45, 15, '8107', 'cultivo para hongos en cualquier muestra diferente a medula', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (46, 16, '8107', 'cultivo para hongos en cualquier muestra diferente a medula', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (47, 17, '45507', 'cultivo rectovaginal', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (48, 17, '8109', 'cultivo germenes comunes', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (49, 17, '1474', 'cultivo para microorganismos en cualquier muestra diferente', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (50, 17, '4144', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (51, 17, '03', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (52, 17, '01', 'tipo de muestra:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (53, 17, '02', 'resultados:', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (54, 18, '45507', 'cultivo rectovaginal', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (55, 19, '01', 'hemocultivo n° 1', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (56, 19, '02', 'observacion hemocultivo n° 1', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (57, 19, '03', 'hemocultivo n° 2', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (58, 19, '04', 'observacion hemocultivo n° 2', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (59, 20, '01', 'hemocultivo n° 1', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (60, 20, '02', 'observacion hemocultivo n° 1', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (61, 20, '03', 'hemocultivo n° 2', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (62, 20, '04', 'observacion hemocultivo n° 2', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (63, 21, '701', 'cultivo para mycobacterium tuberculosis', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (64, 21, '8183', 'mycobacterium tuberculosis  cultivo (no incluye antibiogram', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (65, 22, '8021', 'urocultivo', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (66, 22, '4144', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (67, 22, '2115', 'urocultivo antibiograma de disco incluye el recuento de colo', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (68, 22, '01', 'urocultivo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (69, 22, '02', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (70, 23, '01', 'urocultivo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (71, 23, '02', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (72, 23, '1295', 'urocultivo (antibiograma concentración mínima inhibitoria au', 4, '1', true);
INSERT INTO lab_p_pruebas VALUES (73, 23, '4144', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (74, 23, '8021', 'urocultivo', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (75, 24, '8021', 'urocultivo', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (76, 24, '2116', 'urocultivo antibiograma mic manual incluye el recuento de co', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (259, 56, '07', 'mch', 1, 'Pg', true);
INSERT INTO lab_p_pruebas VALUES (77, 24, '4144', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (78, 24, '01', 'urocultivo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (79, 24, '02', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (80, 25, '12', 'corynebacterium', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (81, 25, '13', 'lactobacillus', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (82, 25, '14', 'cocobacilos gram variables', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (83, 25, '15', 'mobilluncus', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (84, 25, '16', 'otros', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (85, 25, '01', 'exámen físico', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (86, 25, '02', 'fresco: celulas guias', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (87, 25, '03', 'fresco: leucocitos', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (88, 25, '04', 'fresco: blastoconidas', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (89, 25, '05', 'fresco: pseudomicelios', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (91, 25, '07', 'observaciones', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (92, 25, '10', 'exámen microscópico', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (93, 25, '11', 'pmn x campo', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (94, 25, '2079', 'examen directo fresco de cualquier muestra (frotis)', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (95, 25, '5002', 'fresco', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (393, 59, '39', 'monocitos', 1, '%', false);
INSERT INTO lab_p_pruebas VALUES (96, 25, '8041', 'examen directo y fresco de cualquier muestra', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (97, 25, '4144', 'observaciones', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (98, 25, '5003', 'coloracion de gram', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (99, 25, '901304', 'pseudomicelios', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (100, 25, '08', 'trichomonas vaginalis', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (101, 25, 'TESH', 'test de helecho', 2, 'x10^3/uL', true);
INSERT INTO lab_p_pruebas VALUES (102, 25, 'RPM', 'pm', 2, 'SIN UNIDAD', true);
INSERT INTO lab_p_pruebas VALUES (103, 25, '2022', 'trichomonas vaginalis', 2, '', true);
INSERT INTO lab_p_pruebas VALUES (104, 25, 'CORY', 'corynebacterium', 2, 'SIN UNIDAD', true);
INSERT INTO lab_p_pruebas VALUES (105, 25, 'MOB', 'mobiluncus', 2, 'SIN UNIDAD', true);
INSERT INTO lab_p_pruebas VALUES (106, 25, 'BLAS', 'blastoconidias', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (107, 25, 'CGF', 'células guía', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (108, 25, '901303', 'pm', 2, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (109, 25, 'LAC', 'lactobacilos', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (110, 25, 'LEU', 'leucocitos', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (111, 25, 'HEMA F', 'hematies', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (112, 25, 'CBGP', 'coco bacilos gram variables', 2, 'SIN UNIDAD', true);
INSERT INTO lab_p_pruebas VALUES (113, 25, 'CBGV', 'coco bacilos gram variables', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (114, 25, '2016', 'celulas guia', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (115, 26, '47', 'koh', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (116, 26, '696', 'examen directo para hongos (koh)', 4, '1', false);
INSERT INTO lab_p_pruebas VALUES (117, 26, '4144', 'observaciones', 2, '', false);
INSERT INTO lab_p_pruebas VALUES (118, 26, '01', 'koh', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (119, 26, '02', 'observaciones:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (120, 27, '01', 'leptospira', 3, '', true);
INSERT INTO lab_p_pruebas VALUES (121, 27, '02', 'observación:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (122, 28, '01', 'numero de placa', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (123, 28, '2573', 'leishmania examen directo', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (124, 28, '906121', 'leishmaniasis frotis cutanea', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (125, 29, '8058', 'anticoagulante lupico (anticoagulantes circulantes) prueba', 4, '', false);
INSERT INTO lab_p_pruebas VALUES (126, 30, '9012', 'prueba comfirmatoria con veneno vibora de rusell (anticoagu', 4, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (127, 31, '01', 'antitrombina iii por coagulacio', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (128, 32, '1529', 'resultados antes de incubacion a 37°c', 2, 'segundos', false);
INSERT INTO lab_p_pruebas VALUES (129, 32, '1530', 'resultados después de incubación a 37°c', 2, 'segundos', false);
INSERT INTO lab_p_pruebas VALUES (130, 33, '01', 'factor v de la coagulacion labil o proacelina', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (131, 34, '01', 'fibrinógeno', 1, 'mg/dl', true);
INSERT INTO lab_p_pruebas VALUES (132, 34, '02', 'observació', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (133, 34, '1350', 'fibrinogeno', 4, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (134, 35, '902033', 'proteina c de la coagulacion activa', 4, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (135, 36, '6404', 'resistencia a la proteina c activada', 4, 'x10^3/uL', false);
INSERT INTO lab_p_pruebas VALUES (136, 36, '01', 'proteina c de la coagulación:', 1, '', true);
INSERT INTO lab_p_pruebas VALUES (137, 36, '02', 'observacion:', 4, '', true);
INSERT INTO lab_p_pruebas VALUES (138, 37, '01', 'proteina  s  de la coagulacion actividad', 4, '', true);